#!/bin/sh
mkdir -p $HOME/rcarmedia
#REPLACEIT="\/home\/ruinrobo"
#sed "s|$REPLACEIT|${HOME}|g" ympd.conf > $HOME/rcarmedia/ympd.conf
cp ympd.conf $HOME/rcarmedia/
sudo mkdir -p /media/storage/Music
sudo chown -R $USER:$USER /media/storage
sudo apt-get install mpd
sudo touch /var/lib/mpd/tag_cache
